title: Andres Gregori Portfolio
author: Andres Gregori
email: data_services@gregory.mx 


description: >
  Data Scientist/Data Engineer with 5 years of experience. Enthusiast for teaching Data Science related subjects such as Probability, Statistics, and Big Data.  
  Skilled in Python libraries like Pandas, Matplotlib, Plotly, Statsmodels and Scikit-Learn for data manipulation, model building, and visualization. 
  Also well versed in R Programming Language.
  Proven ability to leverage data insights to create effective solutions. 
  Experience with a variety of projects including portfolio optimization, sports analytics, sentiment analysis, and insurance risk prediction.

#logo: /assets/logo.png
theme: jekyll-theme-minimal
markdown: GFM

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
