title: Andres Gregori Portfolio
author: Andres Gregori
email: data_services@gregory.mx 

description: >
  Data Science Enthusiast with a passion for using machine learning and data analysis to solve real-world problems. 
  Skilled in Python libraries like Pandas, Matplotlib, Plotly, Statsmodels and Scikit-Learn for data manipulation, model building, and visualization.
  Proven ability to leverage data insights to create effective solutions.  
  Experience with a variety of projects including portfolio optimization, sports analytics, sentiment analysis, and insurance risk prediction.


theme: jekyll-theme-minimal
markdown: GFM

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
