
title: Andres Gregori Portfolio 
email: data_services@gregory.mx  
description: Data Science Enthusiast with a passion for using machine learning and data analysis to solve real-world problems. Skilled in Python libraries like R and Scikit-Learn for data manipulation, model building, and visualization. Proven ability to leverage data insights to create effective solutions. Experience with a variety of projects including portfolio optimization, sports analytics, sentiment analysis, and insurance risk prediction.


theme: minima 


