title: Andres Gregori Portfolio
author: Andres Gregori
email: data_services@gregory.mx 


description: >
 Data Scientist with 5+ years of experience building models and pipelines that bridge academic rigor and real-world impact. 
  I specialize in statistical inference, machine learning, and optimization — with projects ranging from predicting NFL draft picks 
  and modeling NCAA brackets, to portfolio optimization and experimental lab evaluations.
  My toolkit includes Python (Pandas, Scikit-learn, Plotly, Statsmodels), R (for teaching Probability and Statistics), and cloud tools like GCP and Looker Studio.
  Whether it's identifying undervalued prospects or building AI-powered draft agents, I turn data into decisions.
#logo: /assets/logo.png
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

google_analytics: G-0GPW9JTXQE

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
