title: Andres Gregori Portfolio
author: Andres Gregori
email: data_services@gregory.mx 


description: >
  Over 5 years of experience in data science and engineering, I am adept at transforming data into actionable insights through effective solutions. 
  My proficiency in Python libraries like Pandas, Plotly, Statsmodels, and Scikit-learn for data wrangling, visualization, and machine learning model building.  
  I have experience with R programming which I use to teach Statistics to my students.
  I've tackled projects across diverse domains like portfolio optimization (achieving top 3 weekly on Reto Actinver 2022) and NFL Combine (identifying key factors for players to be drafted). 

#logo: /assets/logo.png
theme: jekyll-theme-minimal
markdown: GFM

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
