# Site settings
title: Andres Gregori Portfolio  # Replace with your name
email: data_services@gregory.mx  # Replace with your email address
description: Data Science Enthusiast with a passion for using machine learning and data analysis to solve real-world problems. 
Skilled in Python libraries like R and Scikit-Learn for data manipulation, model building, and visualization. 
Proven ability to leverage data insights to create effective solutions. 
Experience with a variety of projects including portfolio optimization, sports analytics, sentiment analysis, and insurance risk prediction.


# Theme settings
theme: minima 


plugins:
  - jekyll-paginate  # Pagination for long lists of content


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
