title: Andres Gregori's Portfolio
author: Andres Gregori
email: data_services@gregory.mx 


description: >
Data Scientist with 6 years building analytics systems that drive growth and profitability. 
Currently at NuBank developing association models ($2M opportunity identification) and product roadmaps through A/B testing. 
Previously at Google and Bitso, I have launched analytics products generating $400K MRR and turned 2% projected losses into 3% profit margins.
As an educator at Universidad Panamericana, I teach ML, Big Data, and statistical inference while counseling students for the Bloomberg Trading Challenge
(5th place in Mexico),probabilistic modeling, and RAG systems. 
From predicting draft picks to optimizing portfolios, I combine Bayesian thinking with business acumen.

#logo: /assets/logo.png

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

google_analytics: G-0GPW9JTXQE

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
